// Test action
export const TEST_ACTION = 'TEST_ACTION'
export const TEST_ACTION_SUCCESS = 'TEST_ACTION_SUCCESS'
export const TEST_ACTION_FAILED = 'TEST_ACTION_FAILED'

// Notification actions
export const SHOW_NOTIFICATION_SUCCESS = "SHOW_NOTIFICATION_SUCCESS";
export const SHOW_NOTIFICATION_ERROR = "SHOW_NOTIFICATION_ERROR";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";